#!/bin/bash
echo "Press [CTRL+C] to stop.."

# start some completely benign background daemon to do some __lightweight__work
#    ^ this simulates Alice's server's environment
(sleep 10; bash benign.sh)&

# do the actual work
while :
do
    echo "Calculating pi's 3000 digits..."
    time echo "scale=3000; 4*a(1)" | bc -l | head -n1
	sleep 5
done